dbConfig:
  dbName: spotfood
  port: 27017
  host: localhost

awsConfig:
  accessKey: AKIAQJFI7P4NILKIXKGW
  secretKey: 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
  region: us-east-2

#kafkaProducerConfig:
#  bootstrapServers: localhost:9092
#  keySerializer: org.apache.kafka.common.serialization.StringSerializer
#  valueSerializer: org.apache.kafka.common.serialization.StringSerializer
#
#kafkaConsumerConfig:
#  bootstrapServers: localhost:9092
#  keyDeserializer: org.apache.kafka.common.serialization.StringDeserializer
#  valueDeserializer: org.apache.kafka.common.serialization.StringDeserializer
#  groupId: consumer-group

server:
  applicationConnectors:
    - type: http
      port: 39114
#    - type: https
#      port: 39116
#      keyStorePath: keystore.jks
#      keyStorePassword: "spotfood_server"
#      keyStoreType: JKS
#      validateCerts: false
#      validatePeers: false
  adminConnectors:
    - type: http
      port: 39115

logging:
  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO
  appenders:
    - type: file
      currentLogFilename: dropwizard-activity.log
      threshold: ALL
      archive: true
      archivedLogFilenamePattern: dropwizard-activity-%d.log
      archivedFileCount: 5
      timeZone: UTC
    - type: console
      threshold: ALL
      timeZone: UTC
      target: stdout